# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/python:3.10.1
        environment:
          MYSQL_DATABASE: django_riedslist
          MYSQL_USER: root
          MYSQL_PASSWORD: Mosquito_Gamer_7411
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306


    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y mysql-client
      - run: pip install -r requirements.txt
      - run: python manage.py test
