name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_DATABASE: django_riedsdb
          MYSQL_ROOT_PASSWORD: testrootpass
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        ports: ['3306:3306']
        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        DATABASE_URL: mysql://$user:$pass@localhost/$django_riedslistdb
      run: |
        python manage.py test
